### ISSUE TITLE
Cant pass json array as post body. Data is missing

### ISSUE THREAD

**Issue by asolovev99** [fergalwalsh/pico#17]
server:
```python
@pico.expose()
def store_report(*args, **kwargs):
    return args, kwargs
```
client:
```python
import requests
data = [
    {
        'hello': 'world',
        'number': 23
    },
    {
        'hello': 'me',
        'number': 25
    }
]
print(requests.post('http://127.0.0.1:4242/rest_db/store_report', json=data).content)```

Actual result:
b'[[],{"hello":"number"}]'
Expected result:
b'[[{'number': 23, 'hello': 'world'}, {'number': 25, 'hello': 'me'}],{}]'

**Comment by fergalwalsh** [comment]
Thanks for the clear example. This doesn't work by design because the post body is meant to be a dictionary mapping values to the arguments of the function. To pass this structure you should wrap it in another dictionary like this: `requests.post('http://app2.local.fergalwalsh.com/api/store_report', json={'data': data})`

The result you do get is odd and confusing. Probably we should raise an error if the data is not a dictionary.
